# Generated by Django 4.2.7 on 2025-12-06 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "skills",
                "ordering": ["category", "skill_name"],
            },
        ),
    ]
