# Generated by Django 4.2.7 on 2025-12-06 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyProgress",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("week_number", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hours_spent", models.FloatField(default=0.0)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_progress",
                "ordering": ["-year", "-week_number"],
            },
        ),
    ]
